version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@0.2.0


workflows:
  setup_main_workflow:
    jobs:
      - continuation/continue:
          configuration_path: .circleci/test-continue.yml
          parameters: .circleci/parameters.json
