version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@0.2.0

workflows:
  setup_main_workflow:
    when: 
      equal: [<< pipeline.git.branch >>, "main"]
    jobs:
      - continuation/continue:
          configuration_path: .circleci/first-config.yml
          parameters: .circleci/parameters.json
  setup_nonmain_workflow:
    when:
        equal: [<< pipeline.git.branch >>, "main"]
    jobs:
      - continuation/continue:
          configuration_path: .circleci/second-config.yml